[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CmdStan = "593b3428-ca2f-500c-ae53-031589ec8ddd"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
GADM = "a8dd9ffe-31dc-4cf5-a379-ea69100a8233"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
Stan = "682df890-35be-576f-97d0-3d8c8b33a550"
StanSample = "c1514b29-d3a0-5178-b312-660c88baa699"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"
